### ISSUE TITLE
Filemaker error

### ISSUE THREAD

**Issue by BernhardFW** [dbeandrzej/File-Manager-Provider-AWS-S3#1]
Hi Andrzej,
I tried to integrate S3-Strato server (equal to AWS as they say) and got flwg. error in the console:
JQMIGRATE: Migrate is installed, version 3.3.2
filemanager-component.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'makeUploadRequest')
    at Object.upload (filemanager-component.min.js:1:22970)
    at t._invokeServerUpload (filemanager-component.min.js:1:5093)
    at t.<anonymous> (filemanager-component.min.js:1:4791)
    at Object.success [as callback] (filemanager-component.min.js:1:28356)
    at desktop_all.min.js?v=22.1.0:17:10306
    at O.s.trigger.X.success (desktop_all.min.js?v=22.1.0:17:10437)
    at c (desktop_all.min.js?v=22.1.0:2:28327)
    at Object.fireWith [as resolveWith] (desktop_all.min.js?v=22.1.0:2:29072)
    at l (desktop_all.min.js?v=22.1.0:2:79901)
    at XMLHttpRequest.<anonymous> (desktop_all.min.js?v=22.1.0:2:82355)
    Environment: APEX 22.1.0

**Comment by BernhardFW** [comment]
Hi Andrzej,
in the setup of the (plugins-)items on the APEX upload page I set the provider (plugin) item now properly...
It wud be helpful to hv a bit more detailed documentation how to install.

Now i get the flwg error:

JQMIGRATE: Migrate is installed, version 3.3.2
s3.eu-central-1.s3.hidrive.strato.com/docstore/Q_BAU_Schlussrechnung_umbauen.pdf:1          
Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID
DevTools failed to load source map: Could not load content for https://bfw-design.maxapex.ws/i/libraries/jquery-migrate/3.3.2/jquery-migrate.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE.

And it is not clear to me, which role the PL/SQL_API does play... (???)....  as I can see (almost (??) the same code in the plugin...
For sake of good order I hv installed that package as well.

thank you for ur time looking into this.

BTW: I try to connect to STRATO.DE (located in Berlin) and strato is one of the largest Cloud Provider in Germany:
https://developer.hidrive.com/hidrive-s3-api-reference/

best rgds
Bernhard
